#!/usr/bin/env bash

set -e

download_pyenv()
{
	local git_ssh="https://github.com/yyuu/pyenv.git"
	local pyenv_dir="./pyenv"

	if [ ! -d "${pyenv_dir}" ]; then
        mkdir ${pyenv_dir}
	fi

	# Clone pyenv repository.
	git clone ${git_ssh} ${pyenv_dir}

	# Create cache.
	echo "Create ${pyenv_dir}/cache..."
	mkdir "${pyenv_dir}/cache"
}

download_pyenv

