#!/usr/bin/env bash

set -e

download_pyenv()
{
    local git_ssh="https://github.com/yyuu/pyenv.git"
    local pyenv_dir="./pyenv"

    # Remove old pyenv.
    if [ -d "${pyenv_dir}" ]; then
        rm -rf ${pyenv_dir}
    fi

    # Clone pyenv repository.
    git clone ${git_ssh} ${pyenv_dir}

    # Create cache directory.
    if [ ! -d "${pyenv_dir}/cache" ]; then
        echo "Create ${pyenv_dir}/cache..."
        mkdir "${pyenv_dir}/cache"
    fi
}

